### ISSUE TITLE
WinRTXamlToolkit.Sample.UWP 1.9.4 crashes all the time

### ISSUE THREAD

**Issue by AlexandreCH** [xyzzer/WinRTXamlToolkit#13]
Hello,
I have taken the last version of toolkit to check its usability, but every time I run it, it crashes. 
The program '[18872] WinRTXamlToolkit.Sample.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

I run it on Windows 10 with Visual Studio 2015.
Is it a working version? Previously I used v 1.5.0 it was ok.
--Alex

**Comment by ArcticTempest** [comment]
I can confirm that WinRT XAML Toolkit sample no longer works with Visual Studio 2015 Update 1. It appears something was broken with Windows 10 build 10586 or VS2015U1, but I cannot confirm and requires more investigation by someone more familiar with this library.

Trying to open one of the chart controls in the sample results in an unhandled exception:  

**The program '[3004] WinRTXamlToolkit.Sample.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.**

I am getting reports from users that after upgrading Windows 10 to build 10586, they are unable to open one of my apps, specifically the one that uses the WinRTXamlToolkit. To my surprise, I re-opened my solution yesterday after not working on the app for a couple weeks, and it now throws an error:

**The text associated with this error code could not be found.**

**Cannot deserialize XBF metadata type list as 'Chart' was not found in namespace 'WinRTXamlToolkit.Controls.DataVisualization.Charting'. [Line: 0 Position: 0]**

Note: There have been NO changes to my code since I had last deployed the app to the store, and it was working fine. Suffice to say, this has not been great for my app, as it cannot even be opened anymore, and the charting is a core part of the app.

**Comment by MrDeej** [comment]
Same problem here. After troubleshooting for a whole day i discovered that by removing the WinRTXamlToolkit my Project would work again. My problem was that the designer in VS2015U1 crashed With a remotingexception every time i loaded a page in it, regardless of if the page had References to this Toolkit or not, and there was no way to see that the cause was this toolkit before i recreated the project references in a new project and it showed the same error.

Hope you guys can fix it :)

**Comment by GiantappMan** [comment]
Same problem!

**Comment by xyzzer** [comment]
So, did anyone fix it?

**Comment by BerryJansen** [comment]
I have the same issues with the WinRTXamlToolkit.Controls.DataVisualization.Charting (1.9.4) package.
After loading it from NuGet, my XAML designer crashes with the following error.

System.Runtime.Remoting.RemotingException
[15916] Designer process terminated unexpectedly!

The WinRTXamlToolkit.Controls.Gauge.UWP (1.9.4) is working properly in my projects

I don't have the skill's to fix the problem. If I can help by providing any information please let me know!

With regards,

Berry

**Comment by maynee** [comment]
I have the same problem with the xaml designer.
Just having the toolkit referenced in a project causes the designer to crash with a System.Runtime.Remoting.RemotingException.
However, the controls do function correctly.

**Comment by pawanbhattad** [comment]
This is a very awesome toolkit, but cannot be used as of now. Can you please try to fix this? I don't have expertise so can't help here. Eagerly waiting to get this resolved. Thanks!

**Comment by xyzzer** [comment]
I've made a few minor fixes that seem to fix the Sample crashes on my box. Not sure about designer crashes. I'd need a separate issue with more details - repro steps, sample repro sln, video, etc.

**Comment by pawanbhattad** [comment]
Thanks for resolving this promptly, Appreciate it!
