### ISSUE TITLE
WinRTXamlToolkit.Debugging.UWP 1.9.2 crashes

### ISSUE THREAD

**Issue by corliss** [xyzzer/WinRTXamlToolkit#8]
I upgraded from WinRTXamlToolkit.Debugging to the UWP version on Windows 10. Unfortunately it crashes every time the "Visual Tree" button is pressed.

This seems like the same type of known crash that the non-UWP version had, which I thought was fixed in UWP.

Is this a known issue in the UWP version?

**Comment by xyzzer** [comment]
It is a known issue, but I'm still trying to understand it and collect more evidence to get more get help from the XAML platform team in fixing this.
The problem seems to occur in certain cases when the TreeView control is used. It happens when you use the control on Windows 10 regardless of the version of the app or toolkit (8.1 or 10/UWP).
It seems to at least partially be a timing issue that depends on whether the TreeView control first loads with some items or without any items.

For the debug console - it seems to happen a lot less often if you use DC.ShowVisualTreeAsync() on an existing visual tree rather than showing the debug console first and then clicking on the "Visual Tree" button. I keep fiddling with that code, so you might want to try 1.9.3 to see if that still happens. I'll work on it more tomorrow to see if I can find a better workaround.

If you only use the debug console for basic visual tree navigation - you might want to try the new Live Visual Tree in VS 2015 (VS/Debug/Windows/Live Visual Tree while debugging).

**Comment by xyzzer** [comment]
I think I found the problem and it should be addressed in the 1.9.4 version that's already pushed to git and nuget.
We need to now set ItemTemplate before ItemsSource on the TreeView control.

**Comment by corliss** [comment]
Great. Thanks.

A small request: I use the debugger a lot. The rotation animation when the control restores disturbs my concentration. Would it be possible to eliminate it or expose a parameter to do so? 

Also, I end up pushing the control out of the way a lot because the top and left of the app have much content. A parameter to specify the side to dock the collapsed control to would be very helpful.

**Comment by xyzzer** [comment]
I can do that. I've been trying to figure out the best way of docking/collapsing the console some time ago and then just got too busy to finish it.
I'll switch it off the next time I update the toolkit.

Just curious - have you tried the Live Visual Tree panel in VS? If so - any reason you'd keep using my unpolished toolkit instead of that?

**Comment by corliss** [comment]
Thanks - should I open a separate request for the a) rotation animation and b) dock position?

I did take a look at the Live Visual Tree briefly. Does it support all your debugging functions, including changing property values? I can see properties but don't know how to change them in VS.

**Comment by xyzzer** [comment]
Yes, you need to open the Live Property Explorer
![image](https://cloud.githubusercontent.com/assets/1753264/10519241/cc540688-7319-11e5-8048-cbc9d0c93413.png)

**Comment by corliss** [comment]
Thanks for the bitmap - I was referring to the same pane. Just needed to expand the properties to edit them (the aggregate properties are grayed out, which is what confused me.)

Since this functionality subsumes the debugging toolkit, guess I can start using that instead. Thanks!

**Comment by xyzzer** [comment]
Cool,

I'll be adding some more features to my toolkit that are not in the Live Visual Tree pane - like editing the tree itself at runtime, debugging input events etc, but the VS version is probably more stable and full featured for now. One differentiator that I have right now other than the feature (or limitation) of having the debugger window inside of the app is the ability to track focus which helps find these unwanted tab stop elements.

**Comment by corliss** [comment]
Good to know that. Tracking focus is really helpful.

Thanks for your responses - I do have another unrelated question. Is there a SplitView implementation that allows both vertical and horizontal orientations? I'm thinking of using your CustomGridSplitter but perhaps there's a better option?

**Comment by xyzzer** [comment]
I'm not sure. I am planning though to make some SplitView/Pivot combination to be used for the samples app so that it would work well both on a PC and on the phone without the need to use the burger button.

**Comment by corliss** [comment]
Well I'd certainly be interested in that. Is this something you're definitely doing, and do you have a time frame? My needs are just what is stated above:
- a splitter that supports both orientations, with a move handle. 
- a fixed split position unless moved by the user (i.e. the pane sizes should be influenced by the split position rather than the other way around)
