### ISSUE TITLE
UWP: 1.9.4: Duplicate resource when both packages are added

### ISSUE THREAD

**Issue by corliss** [xyzzer/WinRTXamlToolkit#9]
When WinRTXamlToolkit.UWP and WinRTXamlToolkit.Debugging.UWP are both added to a fresh project, these compiler errors result:

1>MakePri : error 0x80073b0f: Processing Resources failed with error: Duplicate Entry.
1>MakePRI : error 0xdef00532: Conflicting values for resource 'Files/WinRTXamlToolkit.Debugging/Views/VisualTreeView.xbf'

Removing the Debugging package fixes the error.

This seems to be a regression from 1.9.3.

**Comment by xyzzer** [comment]
Interesting. I don't think I'd changed anything that should have caused it.
Any chance you have a 1.9.3 build of the toolkit and 1.9.4 of the debugging nuget?
In any case - it should be fine to have just one.

**Comment by corliss** [comment]
Hm, the project refers to assemblies that in turn refer to an older version of the debugger - haven't updated all projects. But this shouldn't cause a compile-timer error, or could it?

**Comment by xyzzer** [comment]
No repro

**Comment by mircotoepfer** [comment]
Recently i got a build exception on my UWP Project

MakePri : error 0x80073b0f: Processing Resources failed with error: Doppelter Eintrag.
MakePRI : error 0xdef00532: Conflicting values for resource 'System.Design/ClassComments1'

I found a lot of information about the error but no solution. It looks like the error must be in the entry application project but it isn't.
In my case the VS integrated automaticly a reference to System.Activities because a made a mistake.

After i deleted the wrong reference, it works fine again.

**Comment by MelbourneDeveloper** [comment]
I'm getting this error as well.

**Comment by MelbourneDeveloper** [comment]
I'm getting this error again
